### ISSUE TITLE
windows capture device init error -103 since miniaudio 0.9.8

### ISSUE THREAD

**Issue by irmen** [irmen/pyminiaudio#12]
@cameronmaske   @mackron   I've updated the python bindings to the new 0.9.8 miniaudio version. Can you please test these (release 1.8) on windows? 
I'm asking specifically because I ran into an issue with the new version on my windows 10 vm; it can no longer open a capture device. It now errors with a MA_NO_BACKEND (-103) error in ma_device_init().  I don't know why this is or if this is only a problem on my vm...

(it's fine on Linux)

**Comment by mackron** [comment]
Hmm, strange one. Obvious things first - you definitely have a microphone connected? If you don't, this is normal depending on the way in which you call `ma_device_init()`. In your test are you passing in a `ma_context` object? If so, and it's tied to WASAPI (not sure about other Windows backends off the top of my head), it will fail completely if it cannot find a microphone. The reason for this is that the context is tied to a specific backend which means it will not fall back to the null backend in the event that it cannot find a microphone. Passing in NULL for the context should have fallen back to the null backend. Getting this while using NULL for the context, and thus enabling backend fallbacks, would be a very strange error.

(Commit for improving the result code when no device is connected: https://github.com/dr-soft/miniaudio/commit/f1625a02aeeb104d112af79f8cf3ba543b2806d2)

**Comment by irmen** [comment]
Somehow I can't get windows inside my Virtualbox VM to deal with my (usb) microphone properly. 
It gets detected as usb audio input device, but Windows itself and several audio applications only respond with an error when trying to access it, unfortunately.  The same seems to happen with miniaudio.  

I will try later on a real Windows machine.

Yes, I'm passing in a ``ma_context`` but with the backends parameter set to NULL.  (this is also what I'm doing for playback devices, these still work fine btw)

(applying the commit you linked didn't change the response code it is still -103 )

**Comment by mackron** [comment]
Yeah if your using VirtualBox I've had similar issues, only other way around - Windows host and Linux guest. It's definitely sounding like that's the problem, though I'm surprised that error code didn't change. Most likely I'm not propagating the result code properly (will take a look later today).

**Comment by cameronmaske** [comment]
@irmen Updated to `1.8` in my project and everything worked fine out of the box. I'm running Windows 10 natively (i.e. not in a VM).

**Comment by irmen** [comment]
Thanks for reporting that Cameron. Glad it works.  I haven't been able to try it myself yet, but it seems that this is a VM issue.  That makes testing things more difficult for me, unfortunately

**Comment by irmen** [comment]
Confirmed no errors on Windows 10 native system. I'll close this.
