### ISSUE TITLE
adapt to miniaudio 0.10 changes

### ISSUE THREAD

**Issue by irmen** [irmen/pyminiaudio#14]
miniaudio had some  API changes in their new upcoming 0.10 version (currently on a branch)

see https://github.com/dr-soft/miniaudio/issues/129

**Comment by cameronmaske** [comment]
@irmen If you need any assistance (i.e. help porting the codebase, testing, etc) for this, let me know how I can help.

**Comment by irmen** [comment]
Thanks! I've just made a branch for the work on this https://github.com/irmen/pyminiaudio/tree/miniaudio-0.10  and updated it to the (wip) 0.10 miniaudio library files.
First step should be to sync the C header file defintions in build_ffi_module.py  with their new versions from the real headerfiles.

**Comment by irmen** [comment]
@cameronmaske don't know if you already have looked at this, but I've deleted and recreated the branch, this time with the final miniaudio 0.10 library files in there -- so you'll have to resync accordingly if you still have the old branch. Ignore this if you haven't looked at this branch already :)

**Comment by irmen** [comment]
@cameronmaske I've now pushed the first set of changes required to get the library to successfully build against miniaudio 0.10.4 (most recent).  I've commented out some things and left some things TODO (mainly the converter api changes) but if you like you can have a swing at it in the current state, in this branch.
I haven't tried to run it at all yet, just to get it to compile and pass the (few) tests (with some hacks).

**Comment by irmen** [comment]
The lowlevel data conversion api (what used to be the StreamingConverter class) has now become quite problematic to implement.  It's now an iterative API but you still have to consider the "actual converted number of input and output frames".   Because there are also the more high level ma_convert() functions I've decided to ditch this low level conversion api support for now.

TODO:

- expose and support filters
- expose and support waveform and noise generation

**Comment by irmen** [comment]
Changes have been merged back into master branch, and pyminiaudio 1.20 has been released, containing miniaudio 0.10.4 library.

The develop branch for this has been deleted.
