### ISSUE TITLE
Can't get seek_frame to work

### ISSUE THREAD

**Issue by pisarenko-net** [irmen/pyminiaudio#20]
I see that one of the arguments accepted by `stream_file()` function is `seek_frame`. Do I understand correctly this allows seeking to an arbitrary position in a PCM stream? I couldn't get it to work. I get ` ('failed to seek to frame', -2)`. The seek should be performed by `lib.ma_decoder_seek_to_pcm_frame(decoder, seek_frame)`. I'm using the version from master. I'm trying to play a FLAC file but the same thing occurs with other formats.

**Comment by pisarenko-net** [comment]
It also appears to me that seeking is not possible once the playback has started. I mean, there doesn't seem to be a function in the API for it (I acknowledge the binding is not 100% complete). Or did I miss it?

**Comment by irmen** [comment]
I'm not entirely sure but it could be that the decoder from the underlying miniaudio library doesn't support seeking

**Comment by irmen** [comment]
What version of the library did you use?  There has been a fix in the underlying miniaudio library regarding seeking.  You need at least 0.10.19 for that fix so please retry with the current version of the library.

Other than that, if the error still remains after this, there's nothing I can do because the python wrapper simply passes on this call to the underlying miniaudio library. 

And indeed, once the playback has started, you cannot seek anymore. You'll have to stop and restart playback at the desired frame

**Comment by mackron** [comment]
I'm the author of miniaudio. The `ma_decoder` and `ma_device` objects are completely decoupled so whether or not the device is started should be irrelevant. One thing to consider, however, is that you need to make sure your seeking and reading are mutually excluded. So you can't read from the decoder in the audio data callback, but then at the same time perform a seek on another thread, such as the UI thread. Simplest way to do this is to wrap reading and seeking in a mutex.

**Comment by irmen** [comment]
Thanks @mackron for the additional info!   I never considered seeking after playback started to be frank. So it might actually be a limitation of my python wrapper.  Still, the error message is one from the underlying miniaudio library.
I hope @pisarenko-net can find a solution based on the information given above?

**Comment by pisarenko-net** [comment]
Thanks for the responses. I haven't tried fixing it yet but it seems what @mackron said about concurrency is likely the root cause here. I'll report back.

**Comment by irmen** [comment]
@pisarenko-net have you ever been able to resolve your issue ?

**Comment by irmen** [comment]
Closing this, as it seems stale.
Just checked as well - adding seek_frame=200000 to the stream_file in demo1.py works just fine.
