### ISSUE TITLE
FFI build of version v1.37 fails on macOS 10.14

### ISSUE THREAD

**Issue by matiaslindgren** [irmen/pyminiaudio#21]
When installing version v1.37 on macOS 10.14, the following command fails:
```
xcrun -sdk macosx clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -DMA_NO_GENERATION=1 -I/private/var/....../pip-req-build-6w3yp2s_ -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c build/temp.macosx-10.14.6-x86_64-3.8/_miniaudio.c -o build/temp.macosx-10.14.6-x86_64-3.8/build/temp.macosx-10.14.6-x86_64-3.8/_miniaudio.o -g1 -O3 -ffast-math -msse -mfpmath=sse
  error: unknown FP unit 'sse'
  error: command 'xcrun' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for miniaudio
```

```
> clang --version
Apple clang version 12.0.0 (clang-1200.0.32.21)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
```

```
> python3 --version
Python 3.8.2
```

Seems to be working fine after replacing [this line](https://github.com/irmen/pyminiaudio/blob/9e90dab0348a788d9d50138b3ef908043a437b61/build_ffi_module.py#L787) with `compiler_args.extend([ "-msse"])`.

**Comment by irmen** [comment]
Does it work with -msse2  as well? 

I don't have a Mac anymore to test this on.

**Comment by matiaslindgren** [comment]
Just tried with all SSE-versions this CPU supports but the error does not change.

[This](https://stackoverflow.com/questions/19600238/how-do-i-pass-mfpmath-sse-to-llvm-using-clang) suggests the flag is redundant but I didn't have time yet to dig through the Clang docs or source code.

**Comment by matiaslindgren** [comment]
Clarification: it does not compile with -mfpmath with any of the versions. But it does compile without it using all versions. E.g. -msse2, -msse3, and -msse4 all work fine.

**Comment by irmen** [comment]
I'll remove the fpmath option.
