### ISSUE TITLE
How to use pyminiaudio to stream an numpy array that is being generated on the fly

### ISSUE THREAD

**Issue by dchaplinsky** [irmen/pyminiaudio#22]
Hello!

I'm working on a little testbed for signal generation, that looks like that:
<img width="1036" alt="Matplotlib Single Graph 2020-11-04 01-45-06" src="https://user-images.githubusercontent.com/131186/98052638-60c18400-1e3f-11eb-8f85-d85351cd3e26.png">

what I'd like to achieve is constant streaming of a generated waveform (which might change as user is interacting with controls).

Any guidelines how I can implement that with pyminiaudio? Sorry if the question sounds too noobish, but I've glimpsed through the docs and examples and still unclear where do I start.

**Comment by dchaplinsky** [comment]
Figured it out :)

Didn't know that one can send values to generators.

**Comment by irmen** [comment]
nice that you figured it out!  enjoy using the library!
