### ISSUE TITLE
add possibility to pause/continue streams

### ISSUE THREAD

**Issue by irmen** [irmen/pyminiaudio#24]
you should be able to pause/continue streams
also seek during playback?  see #20

**Comment by DataExplorerUser** [comment]
pre-loading a track (so the playing starts immediately when calling play), pause/continue/stop, seeking and volume control would all be useful additions.

**Comment by irmen** [comment]
Volume control is not a feature that will be added soon because essentially this would require postprocessing of the pcm data to multiply it by a <1 factor for simulating volumecontrol. Miniaudio doesn't support adjusting the actual audio backend device volume.

**Comment by irmen** [comment]
Actually, streams by itself cannot be stopped/paused/restarted (unless you program your own callback generator), but the Device already has start() and stop() methods that work.

Can you elaborate a bit on the preloading of a track? I think your program should be responsible for timely supplying audio data itself, as soon as you start a device playback with a stream, you are supposed to be able to supply the audio data.
