### ISSUE TITLE
Question about the module (playback too loud/not sounding as expected)

### ISSUE THREAD

**Issue by Mage102** [irmen/pyminiaudio#26]
Hey I don't know if it's the right place to ask, forgive me if I did something wrong
```
song_folder_path = 'C:\\Users\\BOT\\Music'
song_listing = os.listdir('C:\\Users\\BOT\\Music') # only has .mp3 files

for song in song_list:
    try:
        current_song_path = os.path.join(song_folder_path, song)  # song path
        audio_length = int(miniaudio.get_file_info(current_song_path).duration)

        stream = miniaudio.stream_file(current_song_path)
        print(f"Now playing the song: {song}")

        with miniaudio.PlaybackDevice() as device:
            device.start(stream)
            time.sleep(audio_length) # waiting for the song to end

    except KeyboardInterrupt:
        sys.exit()
```
The mp3 is playing fine but the songs are coming out in loud beats with a little much vibrations too and it sounds weird than played on a normal music player
Please can anyone guide me to how to fix this or is it possible to fix?

**Comment by irmen** [comment]
Your code looks fine.
Perhaps you should investigate system volume settings?
Or try another audio backend? (``backends`` parameter to ``PlaybackDevice``)

Also: what happens when you run the various examples that are available in this repository?

**Comment by Mage102** [comment]
> @Mage102 any luck? what version were you using , was it the most recent one?

@irmen Hi there sorry about the late reply. I was using the latest version at that time of posting this issue. I'm actually new to python and since I couldn't figure out the problem I actually started using `python vlc` library

**Comment by irmen** [comment]
ok , well , then I'll close the issue here.
(personally I have not encountered playback issues)
