### ISSUE TITLE
Bug when parsing stream title in icecast metadata

### ISSUE THREAD

**Issue by MaxDerDeveloper** [irmen/pyminiaudio#31]
I hope my report will be helpfull. Possible fix is at the very bottom

# How I found the bug
I started using your python module a while ago and built my own webradio client with it.
When listening to the radio I noticed some of the song titles were incorrect. Cut off at the end,

I came up with the explanation, that parsing the IceCast metadata was parsed in an inprecise way.
If there was a single quote in the song title as in "Let's" or "It's", your library assumed the string was over.

# Fixing it
In miniaudio.py (line 1156)

`search = re.search("StreamTitle='(.*?)'", metadata, re.IGNORECASE)`
Changing it to
`search = re.search("StreamTitle='([^;]*?)';", metadata, re.IGNORECASE)`
should fix the issue, since we are additionally relying on the semicolon after the single qote.

**Comment by irmen** [comment]
Your regex doesn't cover some other cases. I'll fix it using a more robust approach.
