### ISSUE TITLE
segmentation fault after upgrading to 3.9.6_p2 (gentoo)

### ISSUE THREAD

**Issue by wilderjds** [irmen/pyminiaudio#34]
Device creation throws a segfault if pulseaudio has no available devices

**Comment by irmen** [comment]
hm, a segfault is most likely caused by the underlying C library.   https://github.com/mackron/miniaudio

can you perhaps try to run a pure C program that uses the library and see if that also crashes?

**Comment by irmen** [comment]
@wilderjds can you please re-check with current master?

**Comment by wilderjds** [comment]
Sorry if I disappeared; I have trouble reproducing the issue now. Occasionally, when I switch docks, the daemon gets confused and I end up with zero devices in pulseaudio. If it happens again I'll check with the current release.  Again thanks for your reply.

**Comment by irmen** [comment]
Feel free to re-open this issue if you still encounter it.
