### ISSUE TITLE
Publish binary wheels for most common platforms

### ISSUE THREAD

**Issue by postlund** [irmen/pyminiaudio#36]
As a future improvement, it would be really nice to have pre-built binary wheels for all the most common platforms. Requiring a tool chain both adds to install complexity and install time. This Action sounds very promising:

https://github.com/pypa/cibuildwheel

Can even be combined with this to push to pypi when releasing:

https://github.com/marketplace/actions/pypi-publish

**Comment by irmen** [comment]
doesn't seem to support RaspberryPi though

**Comment by postlund** [comment]
I was under the impression that manylinux for ARM would work. But it might not be the case. There's another action just for api though, so just use that in sequence:

https://github.com/piwheels/piwheels

**Comment by postlund** [comment]
Yey!

**Comment by irmen** [comment]
someone else already had set up the piwheels builds I think

**Comment by postlund** [comment]
Made a workflow for it at least. Since you are the owner on pypi, you need to set it up with the correct API key. But maybe just when creating tags or something.
