### ISSUE TITLE
Set input buffer size

### ISSUE THREAD

**Issue by alexitx** [irmen/pyminiaudio#38]
Is there any way to set the input buffer/block size (or maximum size) for the generator of `stream_any`? The `frames_to_read` parameter only seems to affect the returned number of frames when iterating over it.

I'm looking to decrease the overall latency by reading amount of bytes from the StreamableSource as close as possible to the actually needed amount. Currently for 128 kbps MP3 stream the very first read requests 65536 bytes and subsequent reads 49319 bytes.

**Comment by irmen** [comment]
You can only set a buffer size hint for the audio backend with the ``buffersize_msec`` parameter of the various Device classes.
The number of audio frames required in the generator is dictated by the audio backend from within Miniaudio C library itself.

**Comment by alexitx** [comment]
I see, thanks.
