### ISSUE TITLE
Failed to install on Intel Tiger Lake i7-1165G7

### ISSUE THREAD

**Issue by mazimcoder** [irmen/pyminiaudio#39]
Apparently, the package has an issue on processor Tiger Lake. However, on other older 10gen Intel or Apple CPU are fairly fine. The log below;
===============================================================================

  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bneouj72/miniaudio_fad1f814e7844de3939095f4aa22d943/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bneouj72/miniaudio_fad1f814e7844de3939095f4aa22d943/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-yssz4jg6
       cwd: /tmp/pip-install-bneouj72/miniaudio_fad1f814e7844de3939095f4aa22d943/
  Complete output (18 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  copying miniaudio.py -> build/lib.linux-x86_64-3.8
  running build_ext
  generating cffi module 'build/temp.linux-x86_64-3.8/_miniaudio.c'
  creating build/temp.linux-x86_64-3.8
  building '_miniaudio' extension
  creating build/temp.linux-x86_64-3.8/build
  creating build/temp.linux-x86_64-3.8/build/temp.linux-x86_64-3.8
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DMA_NO_GENERATION=1 -DMA_NO_ENCODING=1 -I/tmp/pip-install-bneouj72/miniaudio_fad1f814e7844de3939095f4aa22d943 -I/tmp/pip-install-bneouj72/miniaudio_fad1f814e7844de3939095f4aa22d943 -I/usr/include/python3.8 -c build/temp.linux-x86_64-3.8/_miniaudio.c -o build/temp.linux-x86_64-3.8/build/temp.linux-x86_64-3.8/_miniaudio.o -g1 -O3 -ffast-math -mtune=native -march=native
  cc1: error: bad value (‘tigerlake’) for ‘-march=’ switch
  cc1: note: valid arguments to ‘-march=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 native
  cc1: error: bad value (‘tigerlake’) for ‘-mtune=’ switch
  cc1: note: valid arguments to ‘-mtune=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm intel x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 generic native
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for miniaudio
  Running setup.py clean for miniaudio
Failed to build miniaudio
Installing collected packages: miniaudio
    Running setup.py install for miniaudio ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bneouj72/miniaudio_fad1f814e7844de3939095f4aa22d943/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bneouj72/miniaudio_fad1f814e7844de3939095f4aa22d943/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-mg5692wf/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/mustafa/.local/include/python3.8/miniaudio
         cwd: /tmp/pip-install-bneouj72/miniaudio_fad1f814e7844de3939095f4aa22d943/
    Complete output (18 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    copying miniaudio.py -> build/lib.linux-x86_64-3.8
    running build_ext
    generating cffi module 'build/temp.linux-x86_64-3.8/_miniaudio.c'
    creating build/temp.linux-x86_64-3.8
    building '_miniaudio' extension
    creating build/temp.linux-x86_64-3.8/build
    creating build/temp.linux-x86_64-3.8/build/temp.linux-x86_64-3.8
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DMA_NO_GENERATION=1 -DMA_NO_ENCODING=1 -I/tmp/pip-install-bneouj72/miniaudio_fad1f814e7844de3939095f4aa22d943 -I/tmp/pip-install-bneouj72/miniaudio_fad1f814e7844de3939095f4aa22d943 -I/usr/include/python3.8 -c build/temp.linux-x86_64-3.8/_miniaudio.c -o build/temp.linux-x86_64-3.8/build/temp.linux-x86_64-3.8/_miniaudio.o -g1 -O3 -ffast-math -mtune=native -march=native
    cc1: error: bad value (‘tigerlake’) for ‘-march=’ switch
    cc1: note: valid arguments to ‘-march=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 native
    cc1: error: bad value (‘tigerlake’) for ‘-mtune=’ switch
    cc1: note: valid arguments to ‘-mtune=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm intel x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 generic native
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bneouj72/miniaudio_fad1f814e7844de3939095f4aa22d943/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bneouj72/miniaudio_fad1f814e7844de3939095f4aa22d943/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-mg5692wf/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/mustafa/.local/include/python3.8/miniaudio Check the logs for full command output.

**Comment by irmen** [comment]
what OS are you compiling on?

**Comment by mazimcoder** [comment]
Ubuntu

**Comment by irmen** [comment]
well, that is very disappointing.
I thought that gcc always understands ``-march=native`` on Linux. 
what version of gcc are you using?

**Comment by irmen** [comment]
Right , this is a bug of gcc on Ubuntu
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100009

I think you'll have to upgrade.

**Comment by mazimcoder** [comment]
gcc 9.3.0, it's the same version

**Comment by irmen** [comment]
Apparently that version in Ubuntu didn't get the fix. You'll have to check your ubuntu packages / bugs / updates for a fix. From what I understand from that bug report you'll need gcc 9.3.1 or newer. 
If ubuntu doesn't provide that, please edit the ``build_ffi_module.py`` file  and remove the ``native`` compiler switches on your system manually.
