### ISSUE TITLE
Popping/ticking sound when pausing/resuming playback

### ISSUE THREAD

**Issue by DataExplorerUser** [irmen/pyminiaudio#41]
There is a popping or ticking sound when pausing or resuming some mp3 files. I have used your example code on Github and only modified it to stop playing after 2.3 seconds. Enclosed you will find an mp3 (renamed to .mov because Github doesn't support the upload of mp3's, so rename to .mp3) to try on your own computer.

https://user-images.githubusercontent.com/54912887/140484568-339f32a1-df2d-437d-acab-4fab5c2fd1a4.mov

The popping/ticking sound happens often, but not always. I wonder whether this has to do with particular mp3 formats or (py)miniaudio. This effect does not happen using other media players on my computer.

In the following short example, you will hear a ticking sound right at the beginning.

https://user-images.githubusercontent.com/54912887/140486808-08140523-dcd0-4929-a600-46f3ab487bdf.mov

As a test, when playing a silent mp3 file, there are no popping/ticking sounds when pausing and resuming.

```Python
# https://github.com/irmen/pyminiaudio/blob/master/examples/playcallbacks.py

"""
Shows a way to react on the end of a stream and device activities.
"""

import miniaudio
import time

def stream_end_callback() -> None:
    print("\nSource stream ended!")


def stream_progress_callback(framecount: int) -> None:
   # print(framecount, ",", end="", flush=True)
    pass

if __name__ == "__main__":
    filename = 'example.mp3'
    filestream = miniaudio.stream_file(filename)
    callbacks_stream = miniaudio.stream_with_callbacks(filestream, stream_progress_callback, stream_end_callback)
    next(callbacks_stream)  # start the generator
    with miniaudio.PlaybackDevice() as device:
        print("playback in background. press enter to exit:\n")
        device.start(callbacks_stream)
        time.sleep(2.3)
    print("Device playback stopped.")
```

**Comment by irmen** [comment]
I don't hear any pops or clicks on my system (Linux, pulseaudio). Not at the start, not during play, not when playback ends.

What OS are you running this on? Perhaps it is something with the audio backend driver. Can't do anything about that. 

It may also be related to the fact that you are suddenly without warning, closing the playback device. If it's just playing a loud sample at that time maybe it "clicks" when suddenly all output is cut off?

Suggestions:
- try the sound conversion routines in pyminiaudio to convert the mp3 to wav , then playback the wav to see if the mp3 decoder in miniaudio has an issue. If so -> head over to the miniaudio project to ask for help there.
- try the example C program(s) from miniaudio C library itself to playback the mp3 file to see if you have the same issue. If so -> head over to the miniaudio project to ask for help there.

There's also this issue on my backlog to implement "better" pause/resume support #24

**Comment by DataExplorerUser** [comment]
I'm running Windows 10. It's not that bad, but it's noticable, which is odd given how well the pyminiaudio runs otherwise. There may be things I'm not doing correctly, so it could be just that. I'm looking forward to the better pause/resume support #24. 

Thank you for the elaborate response!

**Comment by irmen** [comment]
Hm-- have you tried playing with the buffer argument for the PlaybackDevice?

**Comment by DataExplorerUser** [comment]
In case you are interested, my music player repo is https://github.com/bandit-masked/raccoon.

Thanks for all your work on PyMiniAudio and your replies!

**Comment by irmen** [comment]
@DataExplorerUser I see a suspicious thing in your code, it seems that every time the go_play() routine is called, it does a next(generator).  This should only be done _once_ after creating the generator. Otherwise you will throw away audio frames from the already running stream.

**Comment by DataExplorerUser** [comment]
Wow, that was quick! That's for actually going over my code, I wasn't expecting that!

That might explain some of the noise it makes. I'll have a look tomorrow!

**Comment by DataExplorerUser** [comment]
I moved `next(generator)` to the go_load() routine which is only called when a new song is played. It works fine like this. If there are any improvements to the sound quality, the changes are subtle. Either way, `next(generator)` isn't called unnecessarily now, so that's an improvement in code at least.

**Comment by irmen** [comment]
Can you try with another audio backend than the default (which  is probably WASAPI)?

**Comment by DataExplorerUser** [comment]
How would I change the audio backend?

**Comment by irmen** [comment]
use the ``backends`` parameter when creating the device. See api doc in the README

**Comment by DataExplorerUser** [comment]
Finally got around to trying this as I was working on the GUI before.
miniaudio.get_enabled_backends() returns {<Backend.WINMM: 2>, <Backend.WASAPI: 0>, <Backend.CUSTOM: 13>, <Backend.NULL: 14>, <Backend.DSOUND: 1>, <Backend.JACK: 9>}

I tried feeding that into the following line, but that didn't work. 
self.playback_device = miniaudio.PlaybackDevice()

I'm not sure what to feed to PlaybackDevice as a backends variable. Any pointers? Thanks!

**Comment by irmen** [comment]
``device = miniaudio.PlaybackDevice(backends=[miniaudio.Backend.WINMM])``

**Comment by bandit-masked** [comment]
The WINMM and backend work, but specifying either one is no better or worse than the automatically selected backend.

**Comment by DataExplorerUser** [comment]
I uploaded a few videos demonstrating the music player. I'm quite pleased with how it turned out. Thanks to PyMiniAudio (and Dear PyGui), the application is light and works smoothly. Thank you for your help getting it work better and your suggestions!

https://github.com/bandit-masked/raccoon

I'm planning to post the project on r/python tomorrow and include a reference to PyMiniAudio as well of course. If you like the project, I'd appreciate an upvote (I can let you know when I have posted).

**Comment by irmen** [comment]
Nice work!  I'll watch this space.    Have you been able to fix the popping sound eventually?

**Comment by DataExplorerUser** [comment]
Thanks for the compliment!

I have tried swapping the backends, but that didn't make a difference. I haven't looked into it any further. Probably most people won't notice it or care anyway. It could be that my code is somehow wrong, it could be interference between Dear PyGui and pyminiaudio or an issue in miniaudio. I wouldn't know how to investigate in more detail. For now, I'd like to wrap up my project as it has taken quite a bit of time already and see what else I can build.

If you add improvements to pyminiaudio in future that might resolve these issues, I'd be happy to try it out on Windows and let you know.

Thanks again!

**Comment by irmen** [comment]
The animated raccoons are cute btw

**Comment by DataExplorerUser** [comment]
lol -- I agree. null painter did a great job creating those raccoons.

**Comment by DataExplorerUser** [comment]
Found two minor bugs, so I'm postponing posting to reddit a bit.

**Comment by irmen** [comment]
@DataExplorerUser  did you ever publish the software on reddit ?

**Comment by DataExplorerUser** [comment]
Apologies for not updating you (I thought I did). I posted on r/python about 4 months ago.

https://www.reddit.com/r/Python/comments/sp7ddv/my_first_project_raccoon_music_player_cute/

https://www.reddit.com/r/madeinpython/comments/too6zu/raccoon_music_player_cute_raccoons_dancing_around/

https://www.reddit.com/r/DearPyGui/comments/toofa4/raccoon_music_player_cute_raccoons_dancing_around/ 

I was happy with the end result and have not worked on it since.

**Comment by irmen** [comment]
thanks for the links, nice to see you got positive replies!

I don't work on the synthesizer anymore.  

I should update PyMiniaudio sometime to the new library version i suppose, but I'm kinda busy with other things and I ran into some nasty compilation issues with their new release. I should revisit it sometime. Maybe it improves sound quality for you.

**Comment by bandit-masked** [comment]
I was really content with the positive response, especially as it was my first project.

I'm in no rush, but if you'd like me to test it when you have updated to the new release of miniaudio, just let me know whenever.

**Comment by irmen** [comment]
It's a really solid first project, very impressive.

**Comment by bandit-masked** [comment]
Thanks, I appreciate it!

FYI -- I just updated to Pyminiaudio 1.50. It works fine with Raccoon Music Player, but the slight ticks still remain. This is not meant as a bug report or to complain, just to let you know that it seems to be the same in this regard as the previous version of Pyminiaudio.

**Comment by irmen** [comment]
Aww, that's too bad. I kinda hoped it would be fixed by an improvement in the C library. 
Seems like there is something weird going on in the python code after all, but it doesn't occur all the time .....
