### ISSUE TITLE
Support more conservative compiler flags

### ISSUE THREAD

**Issue by postlund** [irmen/pyminiaudio#43]
I originally posted this in #42 but I feel that it is out of place, so I'm creating this issue instead. Pasting the initial text:

---

Somewhat related, but not entirely... Looking over compiler flags is a good idea because I'm hit with issues (in pyatv) from time to time where Home Assistant just crashes (Illegal instruction) when a function in pyminiaudio is called. Home Assistant builds wheels for all their supported platforms, so that people can use their docker images which comes without a compiler. My theory is that when these wheels are built by Actions, they are built on a very new CPU architecture and by tuning for native some optimizations kicks in that use "new" CPU instructions, which makes the resulting binary incompatible with older CPUs. The original problem always seems to be resolved by re-compiling the library manually, but that doesn't really fly when you distribute docker images like this. In most cases it makes most sense to compiler with as many optimizations as possible for the current architecture, but it doesn't work if you are targeting a broader audience. So some way to manually override these would be great.

---

Based on above, I believe that it would be better to be more conservative regarding architecture by default in order to support older platforms. It's never a problem for people compiling binaries by themselves, but it makes it very hard to distribute pre-built binaries as the one building the wheels must do so on an old CPU to accomplish this. Perhaps skip `-march` altogether (should be fine?) or allow manual override via environment variable.

**Comment by irmen** [comment]
I never thought this would be so problematic :(

Unfortunately on systems that do properly support -march , leaving it out , makes the compiler unable to utilize modern cpu features such as vectorized instructions and such.  I've done no measuring on miniaudio decoding but I was thinking why not make the C library as fast as possible because any extra microsecond of delay can be problematic with audio related stuff.

But it looks like it's more hassle than it's worth :thinking:

**Comment by irmen** [comment]
another angle: would it be possible somehow to not have the docker image contain a binary version of the library and instead just compile it as it is needed?

**Comment by postlund** [comment]
The whole point of the system they've built is that you don't have to ship compilers and 3rd party libraries for everything. Home Assistant depends on more than 1000 different packages from pypi, running on lots of different hardware platforms (same goes for performance). The docker image is clean, i.e. barely anything is installed and pypi packages are installed on-demand depending what integrations a user have.

**Comment by nikdoof** [comment]
I'd like to suggest something like the following [patch](https://github.com/nikdoof/pyminiaudio/commit/9ae22210714d4f3715aa4fddffc6fc26d3aae7d5).

This way we allow the compiler to make an intelligent choice regarding platform selection, for x86_64 systems the default of `-march=x86_64` will apply, which will enable SSE and SSE2, so some level of optimisation on the `miniaudio.h` level.

In addition, if that is not enough for the user, they can override the build flags with the `PYMINIAUDIO_EXTRA_CFLAGS` environment variable to add in `-march=native` or their pinned choice of arch or tune flags.

Or, we check if `CFLAGS` environment var is set and don't define any `extra_compiler_args`, as to allow for maximum flexibility for cross compiling and optimisation situations.

**Comment by postlund** [comment]
That looks like something along the line of what I'm thinking 👍

**Comment by irmen** [comment]
should be fixed by #46 now !

**Comment by postlund** [comment]
👍 If you publish a new release, I can release a new version of pyatv and bump in Home Assistant which should give us some feedback if this works as expected or not.
