### ISSUE TITLE
How do we stop the device and exit when the callback runs out of samples?

### ISSUE THREAD

**Issue by ali1234** [irmen/pyminiaudio#51]
All the examples require the user to press enter when playback ends.

How can we make the program exit automatically at the end of playback?

**Comment by irmen** [comment]
That depends on when it is that you consider "the end of playback".

But if you are only playing a single sample, you could just do a sleep() for the length of the sound and then simply exit.
Or look at the "playcallbacks" example that shows how to use a callback that reacts on the end of a stream. The callback could be written in such a way that it ends your program.
