### ISSUE TITLE
_miniaudio.abi3.so: undefined symbol: __atomic_load_8 on raspbian

### ISSUE THREAD

**Issue by thirtytwobits** [irmen/pyminiaudio#52]
I'm trying to get pyminiaudio working on Raspian buster but I get this __atomic_load_8 linker error from the pywheels distro. I cloned your repo and built from source and get the same thing. I've also tried adding `-latomic` and `-l:libatomic.a` and neither of these flags help with the linker error. Any ideas on how I can work around this issue?

**Comment by thirtytwobits** [comment]
Okay, I figured out a work around but not a fix. I manually added "atomic" to the list of libraries in setup.py. The bug remains, the build script doesn't detect if libatomic is needed or not. See the grpc project for an example of how to do this (https://github.com/grpc/grpc/blob/master/setup.py#L205)

**Comment by prairiesnpr** [comment]
I running into the same issue, can you detail the change you made to setup.py and compilation steps?

**Comment by thirtytwobits** [comment]
See https://github.com/irmen/pyminiaudio/blob/master/build_ffi_module.py#L812

I added "atomic" to the libraries list and did a `pip install .` from the source directory while my HA virtualenv was active.

**Comment by prairiesnpr** [comment]
> 

Thanks!  That did the trick, this was the last error I had to correct since moving my venv to python 3.10.  Appreciate the work around.

**Comment by NebzHB** [comment]
@irmen Dear, will this be fixed in a soon-to-be release ?

**Comment by irmen** [comment]
Hmm, reading above it seems that some platforms need to link against libatomic. I'll add it to the library list (8ae0a2aff3dc234071d48ca87faa6954a3729028) . Let me know if this fixes your problem.

**Comment by NebzHB** [comment]
please release it :)

**Comment by NebzHB** [comment]
sorry i can't confirm or deny, i don't have RPI... one of my plugin's user had it, but i revert to 1.40 in prod to avoid that, so not possible to confirm for me... maybe @prairiesnpr  or @thirtytwobits

**Comment by irmen** [comment]
try 1.52.
