### ISSUE TITLE
Run in windows service error

### ISSUE THREAD

**Issue by FellowCode** [irmen/pyminiaudio#54]
Hi, i try run miniaudio in windows service. Get error load DLL.

`
Debugging service TestService - press Ctrl+C to stop.
Error 0xC0000004 - Python could not import the service's module

Traceback (most recent call last):
  File "C:\Projects\PythonSpy\spy.py", line 28, in <module>
    import miniaudio
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\miniaudio.py", line 22, in <module>
    from _miniaudio import ffi, lib
ImportError: DLL load failed while importing _miniaudio: Р?Рч Р?Р°Р№Р?РчР? С?РєР°Р·Р°Р?Р?С<Р№ Р?Р?Р?С?Р>С?.
`

**Comment by irmen** [comment]
looks like the required dll is not in a path that is accessible by your windows service python installation.  Check user privileges or try to run it manually with the same config.

**Comment by irmen** [comment]
This is a windows specific configuration issue.  Closing this.
