### ISSUE TITLE
Other Python library using Miniaudio

### ISSUE THREAD

**Issue by bandit-masked** [irmen/pyminiaudio#55]
FYI: I came across another Python library that uses Miniaudio and offers similar functionality to PyMiniAudio. It's not as easy to pip install, but the functionality and API is quite straightforward.

https://github.com/cheofusi/just_playback

Maybe it's interesting to have a look at the code or even collaborate?

**Comment by irmen** [comment]
Their goal is different, it provides a few high level wrappers to just play an audio file. Pyminiaudio is much more general and is exposing the actual miniaudio API to python programs.

**Comment by bandit-masked** [comment]
That's good to know, thanks. It was just an FYI so that you are aware of the other project.
