### ISSUE TITLE
Missing build dependency: `wheel`

### ISSUE THREAD

**Issue by xloem** [irmen/pyminiaudio#56]
miniaudio install fails for me if I do not install `wheel` first

**Comment by irmen** [comment]
Isn't that supposed to automatically install with ``pip`` ?

**Comment by xloem** [comment]
this was without a venv, in termux on android. termux is kind of a small unix-like distribution using apt within an android app; it might have something wonky.

**Comment by irmen** [comment]
By the way, are you compiling from source or just typing pip install miniaudio?

**Comment by xloem** [comment]
I get `error: invalid command 'bdist_wheel'` from both `pip3 install .` and `python3 setup.py install --user`. I also tried in alpine linux in an emulator and had the same experience.

**Comment by irmen** [comment]
My opinion is that your pip setup is borked if pip itself complains about wheel not being installed, but I'll add it  to the config, see if that helps.

**Comment by irmen** [comment]
try 1.52.

**Comment by xloem** [comment]
installs great !
