### ISSUE TITLE
Weird PlaybackDevice.stop() behavior

### ISSUE THREAD

**Issue by martinosspa** [irmen/pyminiaudio#57]
My code is quite hideous and long to look at so i will just provide the issue
I am using an audio stream with callbacks to play audio, my end_callback method is linked to a method that runs PlaybackDevice.stop() (Also .close() ) but that seems to hang (Hang meaning i get no error, and it seems like the code is running something in the background making next instructions unreachable)

If i try to load another stream without .stop() or .close() i get `miniaudio.MiniaudioError: can't start an already started device`
Any idea on how to fix this? Or this a problem/feature of the library?

EDIT:
After some thorough investigation it seems to hang on line 1385 where ma_device_stop is called
https://github.com/irmen/pyminiaudio/blob/3bd826aa61f0e54e2f5fce5a1bd9d972b46d640c/miniaudio.py#L1381-L1388

**Comment by irmen** [comment]
I find this really hard to answer, because the commands are almost directly going to the underlying C library...

**Comment by martinosspa** [comment]
Yea ended up going to the C docs and learned that, that method is not thread safe

**Comment by irmen** [comment]
Oh... did you make a change to your code ?

**Comment by martinosspa** [comment]
Yes, ended up making my 'AudioHandler' class a whole thread just to have everything work since I am using miniaudio with a UI library (kivy)
