### ISSUE TITLE
Disabling SSL verification with Icecast

### ISSUE THREAD

**Issue by mc-tiu** [irmen/pyminiaudio#64]
Hi,

Is there any way to disable SSL verification when playing with Icecast?

**Comment by irmen** [comment]
What do you mean exactly? Is there a problem?

**Comment by mc-tiu** [comment]
That is exactly what I was looking for. 
I have a stream that does not send a full chain in the certificate, and always fails to play.
I got around it by doing a strace and finding that python was looking for certs in ```/usr/lib/ssl/``` and symlinking that to the correct location. However that's not possible on all devices depending on user permissions. I hate overriding SSL, but 🤷🏾

**Comment by irmen** [comment]
Using this custom SSL context you should now be able to add additional certificate search paths with that as well , I think?  Rather than disabling it altogether?

**Comment by mc-tiu** [comment]
Yes. I didn't even think of that.
