### ISSUE TITLE
Latest release has a problem compiling (missing files `miniaudio.c`)

### ISSUE THREAD

**Issue by bdraco** [irmen/pyminiaudio#67]
https://github.com/home-assistant/core/actions/runs/5073353664/jobs/9112547477?pr=93499
```
Building wheels for collected packages: emoji, miniaudio
  Building wheel for emoji (setup.py): started
  Building wheel for emoji (setup.py): finished with status 'done'
  Created wheel for emoji: filename=emoji-2.4.0-py2.py3-none-any.whl size=350809 sha256=710c36722a9b255fcebbc40fb66c6d2e1a8f598c5c7e6313dbe10d7c84ba1493
  Stored in directory: /tmp/pip-cache/wheels/8c/bf/17/02e400a37d0292f1a44ec18e58cfb29b2db6eb86e9c0c3a03f
  Building wheel for miniaudio (pyproject.toml): started
  Building wheel for miniaudio (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Building wheel for miniaudio (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
Successfully built emoji
Failed to build miniaudio
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      copying miniaudio.py -> build/lib.linux-x86_64-cpython-311
      running build_ext
      generating cffi module 'build/temp.linux-x86_64-cpython-311/_miniaudio.c'
      creating build/temp.linux-x86_64-cpython-311
      building '_miniaudio' extension
      creating build/temp.linux-x86_64-cpython-311/build
      creating build/temp.linux-x86_64-cpython-311/build/temp.linux-x86_64-cpython-311
      gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DMA_NO_GENERATION=1 -DMA_NO_ENCODING=1 -DMA_NO_RESOURCE_MANAGER=1 -DMA_NO_NODE_GRAPH=1 -DMA_NO_ENGINE=1 -I/tmp/pip-install-tmwz_q2a/miniaudio_abaabc2a88b0476e9a7f7e6d19882b30 -I/tmp/pip-install-tmwz_q2a/miniaudio_abaabc2a88b0476e9a7f7e6d19882b30 -I/home/runner/work/core/core/venv/include -I/opt/hostedtoolcache/Python/3.11.3/x64/include/python3.11 -c build/temp.linux-x86_64-cpython-311/_miniaudio.c -o build/temp.linux-x86_64-cpython-311/build/temp.linux-x86_64-cpython-311/_miniaudio.o -g1 -O3 -ffast-math
      build/temp.linux-x86_64-cpython-311/_miniaudio.c: In function ‘_cffi_checkfld__ma_device’:
      build/temp.linux-x86_64-cpython-311/_miniaudio.c:9129:37: warning: initialization of ‘volatile ma_device_state *’ from incompatible pointer type ‘ma_atomic_device_state *’ [-Wincompatible-pointer-types]
       9129 |   { ma_device_state volatile *tmp = &p->state; (void)tmp; }
            |                                     ^
      build/temp.linux-x86_64-cpython-311/_miniaudio.c:9131:27: warning: initialization of ‘volatile float *’ from incompatible pointer type ‘ma_atomic_float *’ [-Wincompatible-pointer-types]
       9131 |   { float volatile *tmp = &p->masterVolumeFactor; (void)tmp; }
            |                           ^
      gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DMA_NO_GENERATION=1 -DMA_NO_ENCODING=1 -DMA_NO_RESOURCE_MANAGER=1 -DMA_NO_NODE_GRAPH=1 -DMA_NO_ENGINE=1 -I/tmp/pip-install-tmwz_q2a/miniaudio_abaabc2a88b0476e9a7f7e6d19882b30 -I/tmp/pip-install-tmwz_q2a/miniaudio_abaabc2a88b0476e9a7f7e6d19882b30 -I/home/runner/work/core/core/venv/include -I/opt/hostedtoolcache/Python/3.11.3/x64/include/python3.11 -c miniaudio.c -o build/temp.linux-x86_64-cpython-311/miniaudio.o -g1 -O3 -ffast-math
      cc1: fatal error: miniaudio.c: No such file or directory
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for miniaudio
ERROR: Could not build wheels for miniaudio, which is required to install pyproject.toml-based projects
Error: Process completed with exit code 1.
```

**Comment by bdraco** [comment]
https://github.com/irmen/pyminiaudio/actions/runs/5072279901/jobs/9109763514

the file is missing during the source distribution build

**Comment by irmen** [comment]
The builds work fine though https://github.com/irmen/pyminiaudio/actions/runs/5072279932  ?

**Comment by bdraco** [comment]
We build wheels for musl and some older 32 bit systems

**Comment by bdraco** [comment]
https://wheels.home-assistant.io/musllinux/

**Comment by irmen** [comment]
I think I fixed it in the 1.59 release.
Also by updating the cibuildwheel task it now also builds Python 3.11 wheels, as well as musl wheels it seems!

**Comment by bdraco** [comment]
Great, thanks for that. I’ll bump the version in Home Assistant when I get back home later today and start a wheel build + report back

**Comment by bdraco** [comment]
Wheels look good.

Thanks for fixing

😄

**Comment by rkakrik** [comment]
Same problem on linux-aarch64-cpython-312:
`Collecting miniaudio
  Using cached miniaudio-1.59.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: cffi>=1.12.0 in /srv/homeassistant/lib/python3.12/site-packages (from miniaudio) (1.16.0)
Requirement already satisfied: pycparser in /srv/homeassistant/lib/python3.12/site-packages (from cffi>=1.12.0->miniaudio) (2.22)
Building wheels for collected packages: miniaudio
  Building wheel for miniaudio (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for miniaudio (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-312
      copying miniaudio.py -> build/lib.linux-aarch64-cpython-312
      running build_ext
      generating cffi module 'build/temp.linux-aarch64-cpython-312/_miniaudio.c'
      creating build/temp.linux-aarch64-cpython-312
      building '_miniaudio' extension
      creating build/temp.linux-aarch64-cpython-312/build
      creating build/temp.linux-aarch64-cpython-312/build/temp.linux-aarch64-cpython-312
      gcc -fno-strict-overflow -DNDEBUG -g -O3 -Wall -march=armv8-a -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -march=armv8-a -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -march=armv8-a -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fPIC -DMA_NO_GENERATION=1 -DMA_NO_ENCODING=1 -DMA_NO_RESOURCE_MANAGER=1 -DMA_NO_NODE_GRAPH=1 -DMA_NO_ENGINE=1 -I/tmp/pip-install-octig979/miniaudio_2987bb44b9b8485bbafddc6ddc469440 -I/tmp/pip-install-octig979/miniaudio_2987bb44b9b8485bbafddc6ddc469440 -I/srv/homeassistant/include -I/usr/include/python3.12 -c build/temp.linux-aarch64-cpython-312/_miniaudio.c -o build/temp.linux-aarch64-cpython-312/build/temp.linux-aarch64-cpython-312/_miniaudio.o -g1 -O3 -ffast-math
      build/temp.linux-aarch64-cpython-312/_miniaudio.c: В функции «_cffi_checkfld__ma_device»:
      build/temp.linux-aarch64-cpython-312/_miniaudio.c:9129:37: ошибка: initialization of «volatile ma_device_state *» from incompatible pointer type «ma_atomic_device_state *» [-Wincompatible-pointer-types]
       9129 |   { ma_device_state volatile *tmp = &p->state; (void)tmp; }
            |                                     ^
      build/temp.linux-aarch64-cpython-312/_miniaudio.c:9131:27: ошибка: initialization of «volatile float *» from incompatible pointer type «ma_atomic_float *» [-Wincompatible-pointer-types]
       9131 |   { float volatile *tmp = &p->masterVolumeFactor; (void)tmp; }
            |                           ^
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for miniaudio
Failed to build miniaudio
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (miniaudio)`

**Comment by irmen** [comment]
@rkakrik this is fixed now
