### ISSUE TITLE
simultaneous recording and playing

### ISSUE THREAD

**Issue by beqabeqa473** [irmen/pyminiaudio#70]
Hello.

Could you tell me if it is possible to record sound from microphone and simultaneously play this data to speakers?

If yes, could you please give me a hint.

Thanks.

**Comment by irmen** [comment]
I don't see why not? 
just read chunks of data from a capture device and write those to the output device.
Conversion is needed of the sample format or sample rate is not identical.

Note I have never tried to implement this myself
