### ISSUE TITLE
pyminiaudio isn't usable with Cython because inspect.isgenerator on Cython generators isn't True

### ISSUE THREAD

**Issue by ell1e** [irmen/pyminiaudio#71]
pyminiaudio isn't usable with Cython audio sources because inspect.isgenerator on Cython generators isn't True:

```
  File "/home/user/.local/lib/python3.11/site-packages/miniaudio.py", line 1402, in start
    raise TypeError("callback must be a generator", type(callback_generator))
TypeError: ('callback must be a generator', <class '_cython_3_0_3.generator'>)
```
It would be nice if this check could be expanded in a way that also supports Cython.

**Comment by ell1e** [comment]
In pyminiaudio version 1.59, this problem still seems to be present if my tests are correct.

**Comment by irmen** [comment]
I know very little about cython.  How could one improve this?

**Comment by ell1e** [comment]
Sadly, I don't know how to check this for Cython either. To be able to use miniaudio, I simply deleted that check on my local copy.

**Comment by irmen** [comment]
Ok that is interesting, this check is the only thing that prevents it from working in cython?

**Comment by ell1e** [comment]
Yup! I use it from a Cython program just fine, passing in a Cython function to generate sound. But it only works if I remove that check.

**Comment by irmen** [comment]
I'll see what I can do about that, then.
