### ISSUE TITLE
Can we have a Python 3.12 binary for Windows?

### ISSUE THREAD

**Issue by ssb22** [irmen/pyminiaudio#72]
Hi, I maintain a Python script to compile DAISY files for the blind, and someone at a charity publishing house is trying to run it on Windows under PyCharm, and they're only a beginner coder so getting them to compile things is probably out of the question.  As part of the process I need to change MP3 files from VBR to CBR.  I'm currently relying on calling out to a LAME binary as a subprocess for this, but getting a trusted LAME binary for Windows when you're not equipped to compile things might be an issue, so I'm thinking of changing my code to use pyminiaudio + lameenc to decode and re-encode the MP3s in Python without needing a LAME binary.  But currently the lameenc pypi package has a CPython 3.12 build for Windows whereas pyminiaudio stops at CPython 3.11, which means it won't work out-of-the-box on the latest PyCharm (they either have to install a compiler chain or get PyCharm to downgrade to Python 3.11).  Would it be possible to add a CPython 3.12 binary build to PyPI?  Thanks.

**Comment by irmen** [comment]
I've just uploaded release 1.60 and this now includes python 3.12 packages.
