### ISSUE TITLE
Steam start point

### ISSUE THREAD

**Issue by tcarroll2** [irmen/pyminiaudio#9]
Would like to have a way to pass the offset time to begin the playback, either in milliseconds or seconds, from the start of the file.

**Comment by irmen** [comment]
not sure if the miniaudio decoders support seeking in an encoded file, but I'll have a look.

**Comment by irmen** [comment]
We have ``ma_decoder_seek_to_pcm_frame`` which I can use. It doesn't seem to work well on mp3 files though, but for wav, flac and ogg it seems to work.
You tell it the frame index to seek to, something which is easily calculated from a start time

**Comment by tcarroll2** [comment]
Actually I found the solution with pydub using pyaudio.

**Comment by irmen** [comment]
well, glad you found a solution.
Still, I've added seek support to pyminiaudio as well in 9b2cfbddac8d37d68f439054aeb43f8309bd3cb4 
I'll create a new pyminiaudio release from this in a few minutes.
